services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: trademill
      POSTGRES_USER: tm
      POSTGRES_PASSWORD: tm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
