kis:
  base-url: ${KIS_BASE_URL}
  app-key: ${KIS_APP_KEY}
  app-secret: ${KIS_APP_SECRET}
  account-no: ${KIS_ACCOUNT_NO}

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tm;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    reactor.netty.http.client: INFO

server:
  port: 8080
