spring:
  datasource:
    url: jdbc:h2:mem:tm
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
server:
  port: 8080
kis:
  base-url: ${KIS_BASE_URL}
  app-key: ${KIS_APP_KEY}
  app-secret: ${KIS_APP_SECRET}
  cano: ${KIS_CANO}
  acnt-prdt-cd: ${KIS_ACNT_PRDT_CD}
  tr-id:
    buy: ${KIS_TR_ID_BUY}
    sell: ${KIS_TR_ID_SELL}
